# .github/release.yml

changelog:
  exclude:
    labels:
      - invalid
      - question
      - duplicate
      - help-wanted
  categories:
    - title: Cambios importantes 🛠
      labels:
        - bug
        - breaking-change
    - title: Nuevas Funciones 🎉
      labels:
        - enhancement
    - title: Otros Cambios
      labels:
        - "*"